# Generated by Django 3.2.2 on 2021-05-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
