# Generated by Django 3.2.2 on 2021-05-12 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depature', models.DateField(auto_now_add=True)),
                ('date_delivered', models.DateField()),
                ('delivered', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received', to='company.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
