# Generated by Django 3.2.2 on 2021-05-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_name'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_delivered',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='delivered',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
    ]
