# Generated by Django 3.2.2 on 2021-05-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210513_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_delivered',
            field=models.DateField(null=True),
        ),
    ]
