# Generated by Django 3.2.2 on 2021-05-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_date_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
