# Generated by Django 3.2.2 on 2021-05-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactions_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='delivered',
            new_name='delivery',
        ),
    ]
